export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const UPDATE_WINDOW_WIDTH = "UPDATE_WINDOW_WIDTH";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const WINDOW_WIDTH_DESKTOP = 1200;
