export const SET_SELECTED_VALUE = "SET_SELECTED_VALUE";
export const ADD_TO_SELECTED_VALUE = "ADD_TO_SELECTED_VALUE";
export const REMOVE_SELECTED_VALUE = "REMOVE_SELECTED_VALUE";
export const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
